server:
  port: 7072
  
spring:
  application:
    name: olive-foundation-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://68.183.95.228:7071/.well-known/jwks.json"

  datasource:
    url: jdbc:mysql://localhost:3306/olive?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: dev
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    hibernate:      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect    
      
logging:
  file:
    name: ./logs/olive-foundation-server.log
